#!/usr/bin/env bash
# Displays the PID and process name of bash processes

# This version will always show at least the current shell
echo "$$ bash"  # This shows the current shell's PID
ps -axo pid,comm | grep bash | grep -v grep | awk '{print $1, $2}'
